### ISSUE TITLE
Launcher crashes when I try to open the game

### ISSUE THREAD

**Issue by StarLight20001** [Xferno2/Hearts-Of-Iron-IV-Launcher#14]
Hello, how are you? I had a problem with .NET Framework when starting the game, I got an error box that said I had to enable JIT Debugging, many pages on the internet told me to put "<system.windows.forms jitDebugging="true" />" in the file "<app name>.exe.config" which was "Hoi4 Launcher.exe.config". After that I didn't get the error, but the Launcher closes and the game doesn't open. 
I put "<system.windows.forms jitDebugging="true" />" at the end of the file, before </configuration>

https://user-images.githubusercontent.com/59401260/147134504-7d616073-58cb-46d8-8844-89d20a8fb33c.mp4

**Comment by Xferno2** [comment]
Hello, it's probably because all of the files need to be in the Hearts of Iron IV root folder not in the debug folder. Just copy everything from Debug in steam/steamapps/common/Hearts of Iron IV.
Let me know if it works.

**Comment by StarLight20001** [comment]
Yes, it worked, I installed it wrong, thank you very much, good work

**Comment by Xferno2** [comment]
No problem, thank you and enjoy the game!
