### ISSUE TITLE
Does this support debug mode?

### ISSUE THREAD

**Issue by Ajairy** [Xferno2/Hearts-Of-Iron-IV-Launcher#2]
On a normal launcher, you can use startup argument -debug to launch the debug mode, however doing so on this launcher through Steam results in game crashing.

**Comment by Xferno2** [comment]
Unfortunately no as far as I know, it doesn't pass the arguments to the game. I will add this soon now that you requested it.

**Comment by Xferno2** [comment]
Done, now it should pass the arguments to hoi4. Let me know in this issue if any bug shows because I haven't tested it a lot.
