### ISSUE TITLE
dlc_load.json?????

### ISSUE THREAD

**Issue by kev-hidalgo** [Xferno2/Hearts-Of-Iron-IV-Launcher#6]
I can perfectly install the launcher and run it but when I go to play the game it doesn't let me and it says that it does not have access to some .json file. Does anyone know why this is and how I can fix it and run the game??? Other than that this seems to be a really cool passion project.

**Comment by Xferno2** [comment]
Have you run the official Paradox Launcher before opening this one?

**Comment by kev-hidalgo** [comment]
> Have you run the official Paradox Launcher before opening this one?

in the folder after I downloaded it i ran the official launcher and opened up everything and made sure it was fully working and then i opened this launcher and it still did not work, is there a specific way im supposed to open the launcher?

**Comment by Xferno2** [comment]
I will see what I can do. The official launcher should've created that file in Documents/Paradox Interactive/Hearts of Iron IV/dlc_load.json for what ever reason for you it doesn't. You can create the file yourself where I wrote you the location or wait until I update the launcher

**Comment by kev-hidalgo** [comment]
where can i find the .json file and where do i put it in to allow the launcher to work?

**Comment by Xferno2** [comment]
I wrote you in the last reply the location. You have to creat there the file called dlc_load.json

**Comment by kev-hidalgo** [comment]
I copied and pasted the file from the documents folder into the root folder for hoi and it still doesn't work, it's just complaining about how it doesn't have "access" to the file. If there's an official reason for this or maybe I'm just dumb idk but I appreciate you helping me.

**Comment by Xferno2** [comment]
You don't have to copy that file to root folder if that file is there that's all that matter and it says you don't have access to it, mby the permission are bad. Try run the launcher as administrator. If it still doesn't work, I will try to help you out when I have some free time. Also some screenshots with root folder, documents folder and the error would be appreciated.

**Comment by kev-hidalgo** [comment]
I ran it as administrator and came across the same problems, here are the screenshots, Thank you for your help
![Screenshot (1)](https://user-images.githubusercontent.com/94037930/141215498-f73dbdf6-c6dd-47dc-8326-d6094cfe92e3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/94037930/141215499-339809ed-db62-4752-b95c-9fff1182748f.png)
![Screenshot (3)](https://user-images.githubusercontent.com/94037930/141215502-71498fed-5a92-4696-9cf4-5044518a4669.png)
![Screenshot (4)](https://user-images.githubusercontent.com/94037930/141215504-9306a59a-6ab6-4b7a-9176-9ef6731d1ae7.png)

**Comment by Xferno2** [comment]
You're welcome!
I know what's the issue here from the error but I only have a vague idea how to fix it. The issue is the you are using OneDrive to store your desktop. Normally that wouldn't be an issue but sometimes OneDrive doesn't sync files to save space, which I'm not sure how to fix it but we will try a few things and if that doesn't work I will look into the code mby there's something I can do rather that you.
1. Open the dlc_load.json in an editor, notepad or notepad++ so that it forces one drive to sync it
2. I found [here](http://ostack.cn/?qa=69455/) by disabling OneDrive save space option it might work
![image](https://user-images.githubusercontent.com/25592644/141254233-9ea3ad2f-0ff7-4835-b0d7-5c87832db2ed.png)

Try these see if anything else changes, also send an attachment with the details from error by pressing the details button.

**Comment by kev-hidalgo** [comment]
So basically, I unchecked the box and now the file finally had access to the dlc_load.json file and it ran. Then I closed it because I didn't to play right now. Then I tried it again and my antivirus was messing the whole thing up and crashing it when I tried clicking play, so I tried excluding the program form the antivirus checker and it still kept crashing everytime I click play. The only thing that shows up now is the "A crash has happened, please report" screen from the Paradox crash reporter. I tried deleting the original HOI4 launcher and downloading it again and it still keeps crashing whenever I press play. I'm going to keep trying but it seems like this program is just not meant for my computer at this point, but I greatly appreciate your help.

**Comment by kev-hidalgo** [comment]
Nevermind, it works now, the problem was that I copied the HOI4 root folder into desktop as to have easier access to the launcher and that didn't let it work but if I go to the actual root folder and run it it does work, thank you so much for your help.

**Comment by Xferno2** [comment]
I'm glad the issue have been fixed!
