### ISSUE TITLE
Launcher has trouble enabling specific mods

### ISSUE THREAD

**Issue by retrogatling** [Xferno2/Hearts-Of-Iron-IV-Launcher#9]
This may align with my last issue: the new descriptor generator works great, (although the mods have no thumbnails, but you probably know that already) but any new mods I have subscribed to will not be enabled upon launching the game. I have already reinstalled both the recent release of the launcher and the game (and launcher) itself, but nothing changes. The launcher enables and disables older mods I've been subscribed to for months perfectly. 

I wanted to private message instead of creating a whole new issue, but apparently that's not even a thing on this website. Sorry about that.

**Comment by Xferno2** [comment]
Don't worry this is why issues are here, you can open as many issues as you want as long as there's a problem. I will probably open a discord for feedback but as of now I don't have time for that. Honestly I didn't get the chance to test that feature as much as I wanted. Also I will not be able to look into this problem for the next few days so expect a patch around the end of next week.

So as I understand new mods appear in the launcher but fail to be enabled when lauching the game and also old mods are working perfectly fine, right?

**Comment by retrogatling** [comment]
That's about it, everything else with the launcher is working fine.

**Comment by Xferno2** [comment]
Alright I will see what I can do, you will find the update referenced here when I fix it.

**Comment by Xferno2** [comment]
I tried the launcher right now, I subscribed to a new mod then started the game without opening the paradox launcher and the mod did show up in my game after enabling the mod in the launcher so I don't know what's wrong for sure but I might try something. Before I do that please delete your mod folder from Documents\Paradox Interactive\Hearts of Iron IV. Let the files generate from my launcher then try the mod again, if the mod doesn't work try an other mod that you recently subscribed to maybe something is bugged with that one. If that still doesn't work I will try to fix it from inside the launcher.

**Comment by retrogatling** [comment]
I have tried this, and now the launcher won't actually open - I've already tried to re-install

**Comment by Xferno2** [comment]
Did you recreate the mod folder in the Hearts of Iron IV documents folder? because launcher won't create it for you

**Comment by retrogatling** [comment]
Yes I have, and the launcher can enable the mods but upon launch no mods will be enabled, because I no longer have any.

**Comment by Xferno2** [comment]
Enable the generate mod files in settings because they will generate that way.
